const motivationalQuotes: String[] = [
    "Believe you can and you’re halfway there.",
    "Don’t watch the clock; do what it does. Keep going.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Push yourself, because no one else is going to do it for you.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Dream it. Wish it. Do it.",
    "Great things never come from comfort zones.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "It always seems impossible until it’s done.",
    "Little things make big days.",
    "Don’t limit your challenges. Challenge your limits.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dreams don’t work unless you do.",
    "The harder the battle, the sweeter the victory.",
    "Stay positive, work hard, make it happen.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Don’t wait for opportunity. Create it.",
    "A little progress each day adds up to big results.",
    "Your only limit is your mind.",
    "Start where you are. Use what you have. Do what you can.",
    "Difficult roads often lead to beautiful destinations.",
    "Don’t be afraid to give up the good to go for the great.",
    "Your limitation—it’s only your imagination.",
    "Work hard in silence, let your success be your noise.",
    "The way to get started is to quit talking and begin doing.",
    "Do what you can with all you have, wherever you are.",
    "Success is not in what you have, but who you are.",
    "The future depends on what you do today.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Great things never come from easy work.",
    "Failure is not the opposite of success; it’s part of success.",
    "A river cuts through rock not because of its power, but because of its persistence.",
    "Don’t fear failure. Fear being in the same place next year.",
    "Opportunities don’t happen. You create them.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Action is the foundational key to all success.",
    "If you get tired, learn to rest, not to quit.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "Work hard, stay humble.",
    "Stay hungry. Stay foolish.",
    "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'",
    "Don’t call it a dream. Call it a plan.",
    "Small progress is still progress.",
    "Make each day your masterpiece.",
    "In the middle of every difficulty lies opportunity.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "Hustle in silence and let your success shout.",
    "The secret to getting ahead is getting started.",
    "Do what you love, and you’ll never work a day in your life.",
    "Don’t let yesterday take up too much of today.",
    "A goal without a plan is just a wish.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Strength grows in the moments you think you can’t go on but you keep going anyway.",
    "Discipline is the bridge between goals and accomplishment.",
    "A winner is a dreamer who never gives up.",
    "Don’t be afraid to start over. It’s a chance to build something better.",
    "Success usually comes to those who are too busy to be looking for it.",
    "If you want it, work for it.",
    "The best way to predict your future is to create it.",
    "Winners are not afraid of losing. But losers are.",
    "Every accomplishment starts with the decision to try.",
    "Strive for progress, not perfection.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "You are stronger than you think.",
    "Doubt kills more dreams than failure ever will.",
    "Learn as if you will live forever, live like you will die tomorrow.",
    "Nothing will work unless you do.",
    "Success doesn’t come easy, but it’s worth it.",
    "Work until you no longer have to introduce yourself.",
    "You don’t get what you wish for. You get what you work for.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Energy and persistence conquer all things.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Don’t fear moving slowly, fear standing still.",
    "Don’t stop until you’re proud.",
    "If people are doubting how far you can go, go so far that you can’t hear them anymore.",
    "You can’t go back and change the beginning, but you can start where you are and change the ending.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "Do something today that scares you—it means you’re growing.",
    "Act as if what you do makes a difference. It does.",
    "The man who has confidence in himself gains the confidence of others.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "You were born to win, but to be a winner you must plan, prepare, and expect to win.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The expert in anything was once a beginner.",
    "Work while they sleep. Learn while they party. Save while they spend. Live like they dream.",
    "Don’t compare your beginning to someone else’s middle.",
    "When you feel like quitting, remember why you started.",
    "Don’t let small minds convince you that your dreams are too big.",
    "Keep going until your idols become your rivals.",
    "Every day is a chance to be better.",
    "Life has no limitations, except the ones you make.",
    "Start each day with a grateful heart.",
    "Don’t decrease the goal. Increase the effort.",
    "Every strike brings me closer to the next home run.",
    "Go the extra mile. It’s never crowded.",
    "Stay focused and never give up.",
    "You are never too old to set another goal or to dream a new dream.",
    "If you’re going through hell, keep going.",
    "A dream becomes a goal when action is taken toward its achievement.",
    "The best view comes after the hardest climb.",
    "Success doesn’t require genius, it requires persistence.",
    "Your passion is waiting for your courage to catch up.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Be stronger than your excuses.",
    "Do not give up, the beginning is always the hardest.",
    "Make your life a masterpiece; imagine no limitations on what you can be, have or do.",
    "Success isn’t about how much money you make, it’s about the difference you make.",
    "A champion is defined not by their wins, but by how they can recover when they fall.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "Don’t wait for inspiration. Be the inspiration.",
    "If you want to lift yourself up, lift up someone else.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Fear kills more dreams than failure ever will.",
    "Don’t count the days, make the days count.",
    "The biggest risk is not taking any risk.",
    "Do what you fear and your fear will disappear.",
    "Nothing is impossible. The word itself says 'I’m possible.'",
    "Don’t follow the crowd. Let the crowd follow you.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Don’t quit. Suffer now and live the rest of your life as a champion.",
    "Where focus goes, energy flows.",
    "You don’t have to be perfect to be amazing.",
    "Start small. Think big. Don’t stop.",
    "The best revenge is massive success.",
    "When you know your worth, no one can make you feel worthless.",
    "Stop doubting yourself. Work hard and make it happen.",
    "Don’t let success get to your head and failure to your heart.",
    "Success is not just about making money. It’s about making a difference.",
    "If opportunity doesn’t knock, build a door.",
    "Success is about creating value, not chasing validation.",
    "Learn to enjoy the journey, not just the destination.",
    "If you stumble, make it part of the dance.",
    "Work on you, for you.",
    "Keep moving forward.",
    "The best preparation for tomorrow is doing your best today.",
    "Never give up, for that is just the place and time that the tide will turn.",
    "Your vibe attracts your tribe.",
    "Be the type of person you want to meet.",
    "Success starts with self-discipline.",
    "Nothing changes if nothing changes.",
    "Don’t stop believing in yourself.",
    "The best time to plant a tree was 20 years ago. The second best time is now."
];


export default motivationalQuotes;